### ISSUE TITLE
Transparent part of PNG is black when blurred

### ISSUE THREAD

**Issue by karlnippoldt** [liamfiddler/eleventy-plugin-lazyimages#11]
I'm using the plugin on some PNGs that have a transparent background; when they are blurred, the transparent part turns black, instead of staying transparent.
<img width="348" alt="Screen Shot 2020-03-22 at 10 00 58 AM" src="https://user-images.githubusercontent.com/7821608/77257283-8ee7b000-6c30-11ea-9245-c114f1211cb1.png">

**Comment by liamfiddler** [comment]
Hi @karlnippoldt 👋 

Thanks for raising this. I'm guessing it's because the placeholder image is a JPEG, which doesn't support alpha channels. Perhaps the plugin should create placeholders as PNG instead?

**Comment by karlnippoldt** [comment]
Yeah, that would make sense to me.

**Comment by liamfiddler** [comment]
This fix for this has been [released in v1.1.0](https://www.npmjs.com/package/eleventy-plugin-lazyimages/v/1.1.0)  🎉 

The placeholder format will now match the source images. A PNG will create a PNG placeholder, a JPEG will create a JPEG placeholder, and so on.

If you're using a cache file (defaults to `.lazyimages.json`) you may need to delete it and run the build again.
