### ISSUE TITLE
preferNativeLazyLoad breaks srcset

### ISSUE THREAD

**Issue by karlnippoldt** [liamfiddler/eleventy-plugin-lazyimages#14]
With `preferNativeLazyLoad` at its default setting of `true`, in browsers where native lazy loading is supported, `srcset` does not work properly. The browser just loads the fallback image. I'm guessing this is since the `srcset` property is changed to `data-srcset`, which the browser doesn't recognize.

**Comment by liamfiddler** [comment]
Good find! I've just pushed a fix & updated the basic example to master - I'll publish to npm in a couple of hours.

In the meantime could you please let me know if the code in master is working at your end?

**Comment by karlnippoldt** [comment]
Yep, looks like it's working for me.

**Comment by liamfiddler** [comment]
Thanks @karlnippoldt 
This fix [has been released in v1.1.1](https://www.npmjs.com/package/eleventy-plugin-lazyimages/v/1.1.1) 🎉
