### ISSUE TITLE
TemplateWriterWriteError - error after installing plugin

### ISSUE THREAD

**Issue by sachinsancheti1** [liamfiddler/eleventy-plugin-lazyimages#15]
Hi Liam,
I just installed your plugin and used it on my site. My default folder for storing all pages are in the `_site` folder.

I referred to the issue https://github.com/liamfiddler/eleventy-plugin-lazyimages/issues/6#issuecomment-600009537 of `transformImgPath` to change it to `_site` and it infact handled the processing of the images.

The problem:
Case 1: pages which did not have images, got processed and placed in the `dist` folder.
Case 2: pages which had images, did NOT get processed and the html files were not there in the `dist` folder.

Further investigating the issue, I realized that the following error threw up
```
`TemplateWriterWriteError` was thrown
> The "path" argument must be of type string. Received null
```

On removing the plugin, everything works just fine. Not sure where the error came up.

**Comment by liamfiddler** [comment]
👋 Hi @sachinsancheti1 

The error message sounds like your custom path transformer is not returning a valid path. Do you have a repo I could take a look at?

**Comment by sachinsancheti1** [comment]
Sorry Liam for the late reply. It is a private repo so shall try to create a repo which recreates this issue. thank you for the quick response.

**Comment by sachinsancheti1** [comment]
hi Liam, I think I figured the problem out. My previous static version of the website had lazyload incorporated. I had an `img` tag with a **`data-src`** in place. The tag looked somewhat like this:
`<img data-src="/images/logo-footer.svg" class="lazyload" alt="Logo" width="200">`

This was causing the rendering issue. On removal of this tag, everything just worked beautifully!

Sorry for the inconvenience caused on this.

**Comment by liamfiddler** [comment]
Thanks for the update - glad to hear it was resolved!
