### ISSUE TITLE
Different lazyloader?

### ISSUE THREAD

**Issue by brycewray** [liamfiddler/eleventy-plugin-lazyimages#18]
Since your plugin allows using a local instance of lazysizes, is there any chance it might also work with a local instance of @verlok’s LazyLoad?

**Comment by verlok** [comment]
Hey @liamfiddler ,
I came by since I was tagged in this issue.

@brycewray mentioned my [LazyLoad](https://github.com/verlok/lazyload) (Github) script, aka [vanilla-lazyload](https://www.npmjs.com/package/vanilla-lazyload) (npm). It's also on [jsdelivr](https://www.jsdelivr.com/package/npm/vanilla-lazyload).

I would be happy to help and work with you if you'd like to integrate vanilla-lazyload, as an option to choose with lazysizes or instead of it.

**Comment by liamfiddler** [comment]
Hi @brycewray 👋 

Absolutely! The [`scriptSrc` configuration option](https://github.com/liamfiddler/eleventy-plugin-lazyimages#configuration-options) allows you to specify which lazyload script you want to use.

By default this plugin uses lazysizes from jsdelivr, but setting the value to `https://cdn.jsdelivr.net/npm/vanilla-lazyload@16.1.0/dist/lazyload.min.js` will switch it to vanilla-lazyload.

I've created [an example project in this repo](https://github.com/liamfiddler/eleventy-plugin-lazyimages/tree/master/example/verlok-vanilla-lazyload), the [key change can be found on this line](https://github.com/liamfiddler/eleventy-plugin-lazyimages/blob/master/example/verlok-vanilla-lazyload/.eleventy.js#L5).

Note: I've used jsdelivr for convenience, but to increase performance you might also consider self-hosting the script and using a relative `scriptSrc` path.

@verlok Thanks for the quick reply, generous offer to help, and the amazing lazyload script! I've been quite happy with lazysizes, but I'm definitely open to trying alternative options 👍

**Comment by verlok** [comment]
Wow that was quick!
And the reply was very complete and exhaustive. 

To optimise for slow connections and fast readers, remember to set the `use_native` option to false (default in LazyLoad) and the `cancel_on_exit` to true. 

This will cancel the loading of images exiting the viewport while loading, boosting the loading speed of the newly entered ones.

**Comment by brycewray** [comment]
> Hi @brycewray 👋
> 
> Absolutely! The [`scriptSrc` configuration option](https://github.com/liamfiddler/eleventy-plugin-lazyimages#configuration-options) allows you to specify which lazyload script you want to use.
> 
> By default this plugin uses lazysizes from jsdelivr, but setting the value to `https://cdn.jsdelivr.net/npm/vanilla-lazyload@16.1.0/dist/lazyload.min.js` will switch it to vanilla-lazyload.
> 
> I've created [an example project in this repo](https://github.com/liamfiddler/eleventy-plugin-lazyimages/tree/master/example/verlok-vanilla-lazyload), the [key change can be found on this line](https://github.com/liamfiddler/eleventy-plugin-lazyimages/blob/master/example/verlok-vanilla-lazyload/.eleventy.js#L5).
> 
> Note: I've used jsdelivr for convenience, but to increase performance you might also consider self-hosting the script and using a relative `scriptSrc` path.

Excellent! Thanks. And, yes, I always self-host, regardless of the script; trying to keep those external requests to a minimum.

**Comment by brycewray** [comment]
> To optimise for slow connections and fast readers, remember to set the `use_native` option to false (default in LazyLoad) and the `cancel_on_exit` to true.
> 
> This will cancel the loading of images exiting the viewport while loading, boosting the loading speed of the newly entered ones.

@liamfiddler: if I'm doing this within your plugin as discussed above (as opposed to just adding the LazyLoad file script at the end of my base template, as I've been doing in the last few days), any ideas how to provide those @verlok -suggested parameters to the LazyLoad script? In a (non-public) test repo I'm working on, here's what I have now in `.eleventy.js`:

```
eleventyConfig.addPlugin(lazyImagesPlugin, {
    appendInitScript: false,
    scriptSrc: './src/assets/js/lazyload.min.js',
    className: 'lazy',
  })
```

**Edit**: On second thought: I don't know that it matters anyway, because I'm still blocked by that issue you and I discussed earlier re the plugin's current inability to handle `.webp` files (since I'm using `eleventy-plugin-local-respimg` to create them). Am assuming that's still dependent on your using Sharp or another lib of that nature, so I think I will defer this for now and return to using my more manual method of using @verlok's script. **But** I am eagerly looking forward to when you **do** support `.webp`, sir, at which time this question **will** be relevant. 😄  Thanks!

**Comment by liamfiddler** [comment]
No problem @brycewray , I'll tag you when we get webp working!

To anyone else facing a similar issue in the meantime; when you set a custom script using `scriptSrc` this plugin will add some code to your output that loads your custom script with the default parameters.

If you need to modify the custom script's parameters the recommended approach is to set `appendInitScript: false` in this plugin's config (like in the previous comment).

`appendInitScript: false` tells the plugin to skip adding the script loader code to the page. It ignores any value set for `scriptSrc` and allows you to use your own method for including the custom script. The plugin will still set the `data-src` + `width` + `height` attributes on IMG tags and generate the low quality image placeholders, it just doesn't manage the actual lazy loading.
