### ISSUE TITLE
lazy image for relative path

### ISSUE THREAD

**Issue by khoivan88** [liamfiddler/eleventy-plugin-lazyimages#22]
Hi thank you for a very useful plugin. I am having some issue with using this plugging for image files that are set as relative path, such what is set in this line: https://github.com/khoivan88/organicchemistrydata/blob/6cc6a51dc4ebf058b1319e81425f9aa79e5b7904/src/hansreich/resources/acronyms/acronyms.html#L12
This plugin works great with all of the images with absolute file path so I'm just wondering if you might know I way I can use the relative path and get your plugin to work?

Thank you very much!

**Comment by liamfiddler** [comment]
👋  Hi @khoivan88 !

This is a tricky problem to solve because eleventy-plugin-lazyimages doesn't know where the template lives in the file structure, or which paths are relative to the root vs relative to the template.

I'm working on a change to the `transformImgPath` config function that will help with this kind of situation (expect it to release in a few weeks).

In the meantime the easiest solution is to change the paths in your template from file-relative to root-relative. For example, from `acronyms_data/statistics.gif` to `/hansreich/resources/acronyms/acronyms_data/statistics.gif`

**Comment by khoivan88** [comment]
hi @liamfiddler ,

I see, thank you very much. I think I can wait for a few weeks. I think this will be a great addition for your plugin and I'm looking forward to it. Thank you very much for your prompt response :)!

**Comment by liamfiddler** [comment]
In v2 of the plugin (just released 🥳 ) we now pass an object as the second argument to `transformImgPath`. The object currently contains one value `outputPath`.

This means you can perform operations based on where the file will be saved.

Here's an example (untested). The part that might be relevant to you is in the first if statement.

```js
// These are the default values, set them to match your 11ty config
const eleventyInputDir = '.';
const eleventyOutputDir = '_site';

eleventyConfig.addPlugin(lazyImagesPlugin, {
  transformImgPath: (src, options) => {
    const isAbsoluteUri =
      src.startsWith('/') ||
      src.startsWith('http://') ||
      src.startsWith('https://') ||
      src.startsWith('data:');

    // If the file path is relative to the output document
    if (src.startsWith('./') || src.startsWith('../') || !isAbsoluteUri) {
      const lastSlashPosition = options.outputPath.lastIndexOf('/');
      const outputDir = options.outputPath.substring(0, lastSlashPosition + 1);
      return `${outputDir}${src}`.replace(eleventyOutputDir, eleventyInputDir);
    }

    // If the file path is relative to the project root
    if (src.startsWith('/') && !src.startsWith('//')) {
      return `.${src}`;
    }

    return src;
  },
});
```

**Comment by khoivan88** [comment]
This is awesome, thank you very much @liamfiddler . I can now enable lazy-plugin in my project again!

**Comment by liamfiddler** [comment]
👍 I'll close this issue for now, but feel free to reopen if the problem persists.
