### ISSUE TITLE
png base 64 image are less compressed

### ISSUE THREAD

**Issue by ixartz** [liamfiddler/eleventy-plugin-lazyimages#32]
I have update my eleventy plugin lazyimage to the latest version and it seems my png base 64 of this image: https://creativedesignsguru.com/demo/Eleventy-Starter-Boilerplate/assets/images/posts/error.png has become bigger.

The old version:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAB90lEQVR4AU3BzUsUYQDA4d8748666q5WC36M62poYpaXIOjjEHQoiIqgPEY37dChDl4KKfoDokMUQV+XyK6Gx4SisIKkRUJcE0tCSvZjxp2Z3Zl337c9eOh5BDtGgf2Q9GPW+JhhHtnT1Rn6PT25j18+z8ekXJkFTYOg4RKQTrUfPNHT+7o/1T5sD2RFKpVCCKGLnhc++LTw+N5q/noEdfM2sGqY9tTR4+8O2PZAd39WxGMWWim0qgtLiKZjmcxho1AIHdd9b7wAzg4O3e1tae2OtSSQVpxtyyL0PUKl8U6fInBccXJg77VBaDNs2NVnmBfcakC14qGzfXRM32Q70Uzi6gRbb+cJKxW6EJ1VyxpuGjLMwaBUbo/SaZAS/80cySgk++ghK0+fYS1+w1MKWZfYmoTRolTT31KRWsUjKDv4rku1UKS0kidz/hzB7g78cplCoShzUm4aefS6G0XBdqlE4DiIrk6ar1wmd3GcjVvTpCYn8ByHXKm4rLX6Zf4ArxvGMkqPWkoRH9nH+stXsLaOu/Sd4uwsNb+qn1S9KRu9aNLwE72QlPJMf12lg+U8+vcm9SiiHkVEYcSMrM3Moe4sgTZpqIG7qtXMloxiSaVGWpWKR1qxhnKfa3n/A/qGByENgv+0gchAXyscqoH6A1892PBAs+Mfoyn2MCSbBxYAAAAASUVORK5CYII=

the new one: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZCAYAAADE6YVjAAAACXBIWXMAAAsSAAALEgHS3X78AAAIK0lEQVRIx1VWCVSURxLuf+YfZmA4lNMBQRAEueWQW0AwiCOoIMglt0c2+9g1SOKBuyvJeiDLiphDXPdFMfEGDdcgIoeCGEARRcCgEBjlGkQx7JqnsWr7Hw7dfq/+6p7p/r6q6u6qJhFkqqF0rVJn6huQmRZMiMoWFaFhulDkuUMgjNvBCtJ3qgh379LQTNuhp78h3Wi+T8o8iWWImlhbnRDBzLozDktmMYJmOq/9ApR6v8kCpZ5HCP8zrTnz/mEg8fvWwDDtX/qSvH8bSM4XmphWXrKxq5a5e5bVBASeublK+nVdsDSrbHng1hNL3QL+Ym5h7EIN4zBGkjfNEpECsVip842nCPzppBwTU4vCRYtjLllaf/2jpXVD2WLbp1WOzv+56en9e0vACri/OvRtZ9j6ye7IqJHOyA3d7eERtbdCQgtK/fw3HbN3cNjA5ytBf/L1f0+UoaOr1NbU5aNW1lbFS1w2X3dxK2508+xv8fR50xHwEfaGrsPB6FgcT0qBV5u24OSWrTi5eStOpG7GoYSkt0+iYwdbQ9dUyfz8tx+3s3daxeeLOMx9EkNClr7n4h0wtzArdfNIaVrmX9YVEDT6JEgKA2vCcDhmI7xIToVXm7dyBECBP5R3r6im5DgQHfuqVRpSV+Ltk5a9yNKSw0REQmqdp2g+1tbRueDkGn7bd/m5J8GrR4bWhMFoRBSMxcXDi8QUfElJXlAvZiUxBcYTk2GM9hWcpqKIi8fH4RHPG1cEXfzB2WV9rLr6nPcuEMLmLbRwq3b3ynkYGNQzFLru3RglUETHwfONCficWjqanIpUQBG7EcfiElAREwdjCUkwlvE5DO/cjYPb0mGQevw0PALaVko7K718srKMTexmSeJU1XTPWNslN3h4X30UEPR6mIZoZP0GGI2KwbHkTfB8z19xdP9BGNqVic/ik3AoPBKHI6Nx7E/b8Pk334KcSu/uTHwSth6G1oZjR1Dwy3of39PHraxXU3hWSbJHR9fxso3d/npnt55H/itwQBoKg2ERMEStGknZhONHjsJ4SRmOXLiIA5/vxP6IKByMT8Tx3MOoKCvHvlOF2EU9eSQNgYHg1dAVGPT7DU/va2ftHFLpkdbgONgcvXnSSxZWhdW2jhMd3n74eEUwyEPXgTxkLT6jIRg7eAgnaurw5b12HKZE8r1f4EhOLiqKL6P88hXs3JsFHevC4ZF/IPQGfATdvsux3tW9ucjWPj1UKNInvoSID+vqJ502WiCrsFj8ttXVA7vo5F9WSqEvaBX0SUNRnpSKirx8nLjZgC9aW3G8rg4VVdfwKUdwMBvvhUdgh9cy6PZcht1ey951unthjYPT/SIrm10xqmpGZD0h2rla2mnHdfQbLxubYaO9E3R4+cLj5Sugxy8Af/bxw5/9ArGX7sEwDc9EQwP+NjqKE3I59p49h+1bPsY7Sz2ww9kNHri44QOnpe/aHV2wysrm/gUzi12xIpER2UgYvWxV9fQjYs2Wc/qGWGNpA+1LPTiroNPdGzl56OqOD6l1v/wxDcdLSvDtq19xcnwc5eXl+CDtz3jHwxvu2jrAXRt7pTRb2mC5qXnLaUPj7aGswIDEEqL7hUC4LVsg+unkHB2sXGAOrQ5O8IBa1r7EFTmr7jk640P/QOzP3INDRcWoaG5BRVsbKhpvYf/p7/E+Pd7N1LDb5pbQvNAS6kwWviuWGNcc09Hf4k6IFgmjnz08duuXDFt7TKwJJZL50GRlA222jnDH2h5aLa2xjXrSQ8PytPA09l28hF15R7DnUA6OlJaioqkJeo4VYAs9jfWUpFFigjIDo8mzOvrnD2pohbFcwvQmRJjB8CP/RnhF+UK110U6BlhPvWmxWAy3zRZhCw1DZ1QsDhQcx/4fS/De/gN4MygYm7yW4SN6T+QXLmDXsQJo2pgA1fNNoVZbH4vm6Paf0JiTS0uE28xdZP5AeF6ZhJd/iBU+O6MxF68aGMEtYzNokBhDs5MrdqdnQG9hIT7IP4o3QtZg9fwFWEeNuU3/a0tIhGaaJOsDg+CqngRLxVpvTqlp3jgkUvsknMc3nL3x0YQx/pTw0rJ4bEOBSP3NFS1drNUzBA7olp0j3ItPhLvb0rEhMgqqzCzwmpYOVKvPxetz9eC6qTlWmZrDVUNjKBOp4xmhWJ4vEH3zKV/gb0SjNEviSYgolTC+26k32aywr1BV4/cKTW28rqkNtXRxvaMT1ixxhmsLF4FMrAVVqppwVaQBlUJ1lKmIQaaiBmUCVTzHiia+4qvIMvmC5HUMo/TihoBm/BOErySiSWZeCmEiMhj2h1xWJP9eKH5boaqBVSJ1qKQiE4qhggMUqCEVqGBVoYIvAhmVUr4Iz/JUJo8ygtt7GHZnIuHZz5RjL+7j8L6e8GlNN00gTMx2HvtdNl/l4Xes6NdigSrIWFWspKAcoIwnhAoqMoZqRgWLGQGcYgQv/0nYpl2EvzeZMJ409apzgNuUSWu69K+aZqFD1ocQk0jChKQx/H1ZDFtxlCd4fJIRTJ5nBHiFgpYotQDPEwGeJOx/vyJs3z7CL6d7ujN2ikCLw/ptOvlOvVIIMxOu2fJiRlMNrc7O1KvEzwgv9++EX5pD+G2HCfskj7ADnD5E+Hfp7+U7CC8vhfASV9KgGHIesEKCzOzDhXuUkGmKqWZL/q+x8wkxoGTuMYSJ+4RamkF4BzlSekAO0PEOank8fed4mRMiIdN7gNN7zDUTKo4fDhKn+xof9Gf2ihqiNZfuFyV1pHNd6dF0oDHhnjdayqLE01ROTPlgkbaScKr9D0AF2YvgvvzwAAAAAElFTkSuQmCC

I suppose the switch from JIMP to sharp increase the file size ?

My old version was "eleventy-plugin-lazyimages": "^1.1.2", and now it is "eleventy-plugin-lazyimages": "^2.0.1",

**Comment by liamfiddler** [comment]
:wave: Hi @ixartz 

Yes, that's correct. [The default resolution of the LQIP was increased in v2](https://github.com/liamfiddler/eleventy-plugin-lazyimages#upgrade-notes).

Setting maxPlaceholderWidth and maxPlaceholderHeight to 12 will restore the previous settings and your placeholder image will reduce in size.

**Comment by ixartz** [comment]
Hi @liamfiddler thank you for your quick response. Now, I understand the reason.
Definitively, love this v2. Even if it did some unpleasant surprise but it support webp ;)

**Comment by liamfiddler** [comment]
I'll close this issue because it seems to be resolved. Feel free to reopen if I'm mistaken.
