### ISSUE TITLE
Cache not loading

### ISSUE THREAD

**Issue by MaybeThisIsRu** [liamfiddler/eleventy-plugin-lazyimages#33]
Hi.

I added a bunch of logging calls to check if the cache was actually being loaded, and turns out this function is never called.
```
const { logMessage } = require('./helpers');

// A global to store the cache data in memory
let lazyImagesCache = {};

// Loads the cache data into memory
exports.load = (cacheFile) => {
  logMessage(`attempting to load cache from ${cacheFile} now...`);
  if (!cacheFile) {
    logMessage('you need to specify a cache file.');
    return;
  }

  try {
    if (fs.existsSync(cacheFile)) {
      const cachedData = fs.readFileSync(cacheFile, 'utf8');
      lazyImagesCache = JSON.parse(cachedData);
      logMessage('cacheFile found and loaded.');
    }
  } catch (e) {
    console.error('LazyImages - cacheFile', e);
  }
};
```

The only call I see is here:

```
// Export as 11ty plugin
module.exports = {
  initArguments: {},
  configFunction: (eleventyConfig, pluginOptions = {}) => {
    lazyImagesConfig = {
      ...defaultLazyImagesConfig,
      ...pluginOptions,
    };

    checkConfig(lazyImagesConfig, defaultLazyImagesConfig);
    cache.load(lazyImagesConfig.cacheFile);
    eleventyConfig.addTransform('lazyimages', transformMarkup);
  },
};
```

This was not the case before the May update which I think involved quite a bit of refactor. I'm on Eleventy v0.11.0

**Comment by liamfiddler** [comment]
👋 Hi @hirusi 

I can't recreate the issue you're describing. I tried copy-pasting the code you supplied into my local copy and it ran as expected.

![Terminal output showing the console.log statements working](https://user-images.githubusercontent.com/4485449/90111003-6011d800-dd91-11ea-8cb0-05f72c200859.png)

Do you have a repo I could look at?

**Comment by MaybeThisIsRu** [comment]
Thanks for such a quick response!

I maintain [a copy of your plugin](https://github.com/liamfiddler/eleventy-plugin-lazyimages/compare/master...hirusi:master) and had [accidentally deleted a required variable declaration](https://github.com/hirusi/eleventy-plugin-lazyimages/commit/16699049379980e73bb939234b4cda678428b19a).

Closing.
