### ISSUE TITLE
attribute only

### ISSUE THREAD

**Issue by tcurdt** [liamfiddler/eleventy-plugin-lazyimages#36]
I don't really need all the features of the plugin. Especially as it does not seem to work with relative image paths.
It would be great if there was a way to configure it to just add the attribute `loading="lazy"` on all images.

**Comment by liamfiddler** [comment]
👋 Hi @tcurdt !

I understand. This plugin isn't a good fit if that's what you're trying to accomplish. I'm currently working on another eleventy plugin that will address this need - I'll post a link here when it's released.

Also, keep an eye out for the next release of this plugin; it will have better support for relative paths 👍

**Comment by liamfiddler** [comment]
🚀 The other eleventy plugin I mentioned in my previous comment has now been released! [Check it out on npm](https://www.npmjs.com/package/eleventy-plugin-transformdom) or jump straight to [the `loading="lazy"` example](https://github.com/liamfiddler/eleventy-plugin-transformdom/blob/5ce2163e0aa095467550b5256e715f9263dece32/examples/loading-lazy/.eleventy.js).

AND I've also just released [version 2.1 of this plugin](https://www.npmjs.com/package/eleventy-plugin-lazyimages#v210) which better handles relative file paths 😃
