### ISSUE TITLE
Polyfill fix for IE?

### ISSUE THREAD

**Issue by brycewray** [liamfiddler/eleventy-plugin-lazyimages#4]
This is a great plugin; thanks very much. One question: do you have a best-practices method  to incorporate a LazySizes-style polyfill fix for Internet Explorer?

**Comment by liamfiddler** [comment]
Thanks for the kind words Bryce 😄 

As of https://github.com/liamfiddler/eleventy-plugin-lazyimages/commit/822b982fbf93e8775af1b9d3530bc28a5f8a7d00 eleventy-plugin-lazyimages will work in Internet Explorer 9+
