### ISSUE TITLE
Disable lazy loading for certain images

### ISSUE THREAD

**Issue by dimejo** [liamfiddler/eleventy-plugin-lazyimages#59]
Is it possible to disable lazy loading for certain images by e.g. adding a class?

**Comment by liamfiddler** [comment]
👋 Hi Dimejo!

Yes, the `imgSelector` config option allows you to specify a selector for targeting which images get lazy loaded.

Using the `:not` pseudoselector we can ignore all IMG elements that have a class.

For example, the following will add lazy loading to all IMG elements except those with the `class="ignore-lazy"`:

```js
eleventyConfig.addPlugin(lazyImagesPlugin, {
  imgSelector: 'img:not(.ignore-lazy)',
});
```

**Comment by dimejo** [comment]
That's awesome, thank you so much!
