### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by nothingrandom** [liamfiddler/eleventy-plugin-lazyimages#6]
Can't get this to work with images as part of the build process. I think there's some path issues.
See that none of your examples allow for this - is that intentional?

**Comment by liamfiddler** [comment]
Hi @nothingrandom 👋 

Images should be working - both locally and when pulled from a third-party server. To demonstrate this I've added some local images to the "basic" example.

Take a look at [this commit](https://github.com/liamfiddler/eleventy-plugin-lazyimages/commit/c97767478767c8400116fd45f7b8f2dbd62c1d6b) to see what's changed.

Let me know if this example helps, or if you have a public repo I could look at 😃

**Comment by nothingrandom** [comment]
Hey!
Thanks for the quick reply :) It does help somewhat, I think I now see the issue.

I think one of the big differences might be the project structure. My structure is like this;
```
.
├── .editorconfig
├── .eleventy.js
├── .eslintrc.js
├── .git/
├── .gitignore
├── .lightserverrc
├── .npmrc
├── .nvmrc
├── .snyk
├── .travis.yml
├── .typo-ci.yml
├── README.md
├── _redirects
├── dist/
├── netlify.toml
├── node_modules/
├── package.json
├── postcss.config.js
├── src/
│   ├── _data/
│   ├── _includes/
│   ├── browserconfig.xml
│   ├── css/
│   ├── favicon.ico
│   ├── fonts/
│   ├── img/
│   ├── js/
│   ├── pages/
│   └── site.webmanifest.njk
├── utils/
│   ├── filters.js
│   └── shortcodes.js
├── webpack.config.js
├── yarn-error.log
└── yarn.lock
```

So .eleventy.js is in the root, files and images are both in `src/`, and the project is building into the `dist/`

Should I do something to fix this my end, or does this want to be a plugin change, with some more support for folder structure?

**Comment by liamfiddler** [comment]
OK, I think I understand now.

The [`transformImgPath` configuration option ](https://github.com/liamfiddler/eleventy-plugin-lazyimages#configuration-options) might help. It allows you to specify a function that points the plugin to the internal image path.

Something like this might work for you (untested):

```js
// .eleventy.js
module.exports = (eleventyConfig) => {
  eleventyConfig.addPlugin(lazyImagesPlugin, {
    transformImgPath: (imgPath) => {
      if (imgPath.startsWith('/') && !imgPath.startsWith('//')) {
        return `./src${imgPath}`;
      }

      return imgPath;
    },
  });
```

**Comment by nothingrandom** [comment]
Yep, that worked perfect. Thank you very much!
